[build]
builder = "nixpacks"

[deploy]
startCommand = "gunicorn --timeout 600 --workers 1 --threads 8 --max-requests 1000 --preload app:app"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "always"
